emotion_icon = {
    '😀': "positive", '😬': "positive", '😁': ' positive ', '😂': "positive ",
    '😃': "positive", '😄': "positive", '🤣': "positive", '😅': "positive", '😆': "positive", '😇': "positive",
    '😉': "positive", '😊': "positive",  '🙂': "positive", '🙃': "positive", '☺': "positive", '😋':' positive ',
    '😌': ' positive ', '😍': ' positive ', '😘': ' positive ', '😗': ' positive ', '😙': ' positive ',
    '😚': ' positive ', '🤪': ' positive ', '😜': ' positive ', '😝': ' positive ',
    '😛': ' positive ', '🤑': ' positive ', "😎": "positive", "🤓": "positive", '🧐': ' positive ', '🤠': ' positive ',
    "🤗": "positive", "🤡": "positive", "😏": "negative", "😶": "negative", "😐": "negative", "😑": "negative",
    "😒": "negative", "🙄": "negative", "🤨": "negative", "🤔": "negative", "🤫": "negative", '🤭': ' positive ',
    '🤥': ' negative ', '😳': ' positive ', '😞': ' negative ', '😟': ' negative ', '😠': ' negative ',
    '😡': ' negative ', '🤬': ' negative ', '😔': ' negative ', '😕': ' negative ',
    '🙁': ' negative ', '☹': ' negative ', "🤢": "negative", "🤧": "negative", '😴': ' positive ', '💤': ' positive ',
    "😈": "negative", "👿": "negative", "👹": "negative", "👺": "negative", "💩": "negative", "👻": "positive",
    "💀": "negative", "☠": "negative", "👽": "negative", "🤖": "positive", "🎃": "positive", '😺': ' positive ',
    '😸': ' positive ', '😹': ' positive ', '😻': ' positive ', '😼': ' positive ', '😽': ' positive ',
    '🙀': ' negative ', '😿': ' negative ', '😾': ' negative ', '👐': ' positive ',
    '🤲': ' positive ', '🙌': ' positive ', "👏": "positive", "🙏": "positive", '🤝': ' positive ', '👍': ' positive ',
    "👎": "negative", "👊": "positive", "✊": "positive", "🤛": "positive", "🤜": "positive", "🤞": "positive",
    "✌": "positive", "🤘": "positive", "🤟": "positive", "👌": "positive", "👈": "positive", '👉': ' positive ',
    '👆': ' positive ', '👇': ' positive ', '☝': ' positive ', '✋': ' positive ', '🤚': ' positive ',
    '🖐': ' positive ', '🖖': ' positive ', '👋': ' positive ', '🤙': ' positive ',
    '💪': ' positive ', '🖕': ' negative ', '✍': "positive", '🤳': "positive", '💅': ' positive ', '👄': ' positive ',
    '👅': "positive", '👂': "positive", '👃': "positive", '👁': "positive", '👀': "positive", '🧠': "positive",
    '👤': "negative", '👥': "negative", '🗣': "negative", '👶': "positive", '🧒': "positive", '👦': ' positive ',
    '👧': ' positive ', '🧑': ' positive ', '👨': ' negative ', '🧔': ' negative ', '👱‍♂️': ' positive ',
    '👩': ' positive ', '👱‍♀️': ' positive ', '️🧓': ' positive ', '👴': ' positive ',
    '👵': ' positive ', '👲': ' positive ', '👳‍♀️': "positive", '👳‍♂️': "positive", '🧕': ' positive ', '🤶': "positive ",
    '🎅': "positive", '👼': "positive", '👸': "positive", '🤴': "positive", '👰': "positive", '🤵‍♀️': "positive",
    '🤵': "positive", '🕴️‍♀️': "positive", '🕴': "positive", '🧙‍♀️': "positive", '🧙‍♂️': "positive", '🧝‍♀️': ' positive ',
    '🧝‍♂️': ' positive ', '🧚‍♀️': ' positive ', '🧚‍♂️': ' positive ', '🧞‍♀️': ' positive ', '🧞‍♂️': ' positive ',
    '🧜‍♀️': ' positive ', '🧜‍♂️': ' positive ', '🧛‍♀️': ' positive ', '🧛‍♂️': ' positive ',
    '🧟‍♀️': ' positive ', '🧟‍♂️': ' positive ', '🙇‍♀️': "positive", '🙇‍♂️': "positive", '💁‍♀️': ' positive ',
    '💁‍♂️': "positive ",  '🙅‍♀️': "negative", '🙅‍♂️': "negative", '🙆‍♀️': "positive", '🙆‍♂️': "positive",
    '🤷‍♀️': "negative", '🤷‍♂️': "negative", '🙋‍♀️': "positive", '🙋‍♂️': "positive", '🤦‍♀️': "negative",
    '🤦‍♂️': "negative", '🙎‍♀️': "positive", '🙎‍♂️': ' positive ',
    '🙍‍♀️': ' positive ', '🙍‍♂️': ' positive ', '💇‍♀️': ' positive ', '💇‍♂️': ' positive ', '💆‍♀️': ' positive ',
    '💆‍♂️': ' positive ', '🤰': ' positive ', '🤱': ' positive ', '🚶‍♀️': ' positive ',
    '🚶‍♂️': ' positive ', '🏃‍♀️': ' positive ', '🏃‍♂️': "positive", '👫': "positive", '👬': ' positive ',
    '👭': "positive ", '💑': "positive", '👩‍❤️‍👩': "positive", '👨‍❤️‍👨': "positive", '💏': "positive",
    '👩‍❤️‍💋‍👩': "positive", '👨‍❤️‍💋‍👨': "positive", '❤': "positive", '🧡': "positive", '💛': "positive",
    '💚': "positive", '💙': "positive", '💜': ' positive ', '🖤': ' positive ', '💔': ' negative ',
    '❣': ' positive ', '💕': ' positive ', '💞': ' positive ', '💓': ' positive ', '💗': ' positive ',
    '💖': ' positive ', '💘': ' positive ', '💝': ' positive ', '💟': ' positive ', '🌼': ' positive ',
    "🚫": "negative", 'like': ' positive', '💌': ' positive ', ':(': ' negative ', '?': ' ? ',
    '💯': ' positive ', '^^': ' positive ', ':((': ' negative ', '️🆗️': ' positive ', ':v': '  positive ',
    '=))': '  positive ', ':3': ' positive ', '❌': ' negative ', ';)': ' positive ','(y)': ' positive',
    '<3': ' positive ', ':))': ' positive ', ':)': ' positive ', ': ) )': ' positive ', ': )': ' positive ',
    '^ ^': 'positive', '^_^': 'positive', ':V': 'positive', ';))': 'positive', ': D': ' positive', ': P': 'positive',
    '= . =': 'negative', '=.=': 'negative', "=='": 'negative', '^ o ^': 'positive', '^o^': ' positive',
    'haizzz': 'negative', 'haiz': 'negative', 'haizz': 'negative', 'kkk': 'positive',
    'he he': ' positive ', 'hehe': ' positive ', 'hihi': ' positive ', 'haha': ' positive ',
    'hjhj': ' positive ', ' lol ': ' negative ', 'huhu': ' negative ', ' 4sao ': ' positive ', ' 5sao ': ' positive ',
    ' 1sao ': ' negative ', ' 2sao ': ' negative ', 'kaka': 'positive', 'ka ka': 'positive', 'ka ka ka': 'positive'

}
wrong_items = {
    ' acc ': ' tài_khoản ', ' fb ': ' facebook ', ' ad ': ' admin ', ' ahbp ': ' anh_hùng_bàn_phím ',
    ' atsm ': ' ảo_tưởng_sức_mạnh ', ' avt ': ' ảnh_đại_diện ', ' ava ': ' ảnh_đại_diện',' ac ': ' anh_chị ',
    ' bb ': ' tạm_biệt ',  ' bla bla ': ' vân_vân ', ' bsvv ': ' buổi_sáng_vui_vẻ ', ' bùng ': ' không_trả_tiền',
    ' fa ': ' cô_đơn ', ' nn ': ' ngủ_ngon ', ' pr ': ' quảng_cáo ',' bn ': ' bao_nhiêu ',
    ' pp ': ' tạm_biệt ',  ' bth ': ' bình_thường ', ' bt ': ' biết ',' cute ': ' dễ_thương ',
    ' chs ': ' chả_hiểu_sao ', ' cmt ': ' bình_luận ', ' ccmnr ': ' chuẩn ', ' đhn ': ' đéo_hiểu_nỗi ',
    ' đhs ': ' đéo_hiểu_sao ', ' g9 ': ' ngủ_ngon ', ' hpbd ': ' sinh_nhật_vui_vẻ ',
    ' snvv': ' sinh_nhật_vui_vẻ ', ' ib ': ' nhắn_tin_riêng ', ' kb ': ' kết_bạn ', ' sml ': ' sấp_mặt_luôn ',
    ' dz ': ' đẹp_trai ',' dth ': ' dễ_thương ', ' dt ': ' dễ_thương ',  ' ex ': ' người_yêu_cũ ',
    ' klq ': ' không_liên_quan ', ' mem ': ' thành_viên ', ' mng ': ' mọi_người ', ' mn ': ' mọi_người ',
    ' nx ': ' nhận_xét ', ' nyc ': ' người_yêu_cũ ', ' omg ': ' oh_my_god ', ' ps ': ' ghi_chú ',
    ' qtqđ ': ' quá_trời_quá_đát ', ' rep ': ' trả_lời ', ' scđ ': ' sao_cũng_được ', ' ố cê ': ' ok ',
    ' stt ': ' trạng_thái ', ' sub ': ' phụ_đề ', ' tag ': ' gắn_thẻ ', ' tđn ': ' thế_đéo_nào ',
    ' troll ': ' chơi_khăm ', ' vs ': ' với ', ' ny ': ' người_yêu ', ' plz ': ' năn_nỉ ', ' app ': ' ứng_dụng ',
    ' nt ': ' nhắn_tin ', ' trc ': ' trước ',  ' t ': ' tôi ', ' m ': ' mình ',
    ' cs ': ' cuộc_sống ', ' ố kê ': ' ok ', ' kp ': ' không_phải ', ' ô cê ': ' ok ', ' giề ': ' gì ',
    ' zth ': ' dễ_thương ', ' ô kêi ': ' ok ', ' okie ': ' ok ', ' o kê ': ' ok ', ' okey ': ' ok ', ' ôkê ': ' ok ',
    ' oki ': ' ok ', ' ote ':  ' ok ', ' okay ': ' ok ', ' okê ': ' ok ', ' oke ': ' ok ', ' ố sì kê ': ' ok ',
    ' khong ': ' không ', ' not ': ' không ', ' kh ': ' không ', ' kô ': ' không ', ' hok ': ' hông ',
    ' ko ': ' không ', ' hk ': ' hông ', ' k ': ' không ',  ' gút gút ': ' tốt ',
    'kg ': ' không ', 'not': ' không ', ' kg ': ' không ', '"k ': ' không ',
    'kô': ' không ', 'hok': ' không ', '"ko ': ' không ' ,' mik ': ' mình ', ' mìn ': ' mình', ' mềnh ': ' mình ',
    'khong': ' không ', ' mk ': ' mình ', ' wá ': ' quá ', ' qá ': ' quá ', ' tẹc vời ': ' tuyệt_vời ', ' tiệc dời ': ' tuyệt_vời ',
    ' tẹc zời ': ' tuyệt_vời ', ' đc ': ' được ', ' dc ': ' được ', ' j ': ' gì ', ' nhg ': ' nhưng ', ' lm ': ' làm ',
    ' nv ': ' nhân_viên ', ' sv ': ' sinh_viên ', ' hs ': ' học_sinh ', ' đt ': ' điện_thoại ', ' ng ': ' người ',
    ' màng hình ': ' màn_hình ', ' màn hìn ': 'màn_hình', ' tet ': ' kiểm_tra ', ' test ': ' kiểm_tra ',
    ' tét ': ' kiểm_tra ', ' sg ': ' sài_gòn ', ' nvien ': ' nhân_viên ', ' siu ': ' siêu ', ' pải ': ' phải ',
    ' fai ': ' phải ', ' fải ': ' phải ', ' ph ': ' phải ', ' h ': ' giờ ', ' sd ': ' sử_dụng ', ' f ': ' phải ',
    ' of ': ' của ', ' kon ': ' con ', ' way ': ' quay ', ' s ': ' sao ', ' cã ': ' cả ', ' v ': ' vậy ',
    ' r ': ' rồi ', ' kiu ': ' kêu ', ' tl ': ' trả_lời ', ' thik ': 'thích', ' thíc ': 'thích', ' ns ': ' nói ',
    ' nviên ': ' nhân_viên ', ' nhiu ': ' nhiêu ', ' oder ': ' gọi_món ', ' ỏder ': 'gọi_món', ' hỉu ': ' hiểu ',
    ' film ': 'phim', ' phin ': ' phim ', ' fim ': ' phim ', ' nh ': ' nhưng ', ' hnay ': ' hôm_nay ',
    ' nhìu ': 'nhiều', ' qay ': ' quay ', ' nc ': ' nói_chuyện ', ' nch ': ' nói_chuyện ', ' tp ': ' thành_phố ',
    ' lun ': ' luôn ', ' rất tiết ': ' rất_tiếc ', ' rất tiêc ': ' rất_tiếc ', ' toẹt zời ': ' tuyệt_vời ',
    ' thất zọng ': ' thất_vọng ', ' thất dọng ': ' thất_vọng ', ' nhưg ': ' nhưng ', ' ms ': ' mới ',
    ' so ciu ': ' dễ_thương ', ' iu ': ' yêu ', ' hn ': ' hôm_nay '


}
"""nagation_items = {
    'không': 'không', 'chẳng':'không', 'chả':'không', 'đâu có': 'không', 'nào có': 'không',
    'khỏi': 'không', 'miễn': 'không','cóc': 'không', 'đếch': 'không', 'đéo': 'không',
    'ứ': 'không', 'chưa': 'không', 'hổng': 'không', 'hông': 'không', 'đách': 'không',

}"""